export enum RequestEnum {
    STATUS = 'STATUS',
    INTENSITY = 'INTENSITY',
    WIFI_CREDENTIALS = 'WIFI_CREDENTIALS',
    SWITCH_TRANSPORT = 'SWITCH_TRANSPORT',
    TRANSPORT_CONFIG = 'TRANSPORT_CONFIG'
}